---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2022/7/26 11:22
---
-- 从Redis中取出来的id
local id=redis.call('get',KEYS[1])
-- 用redis的ID和传进来的ID比较，如果成功会自动return1
if(id==ARGV[1]) then
    return redis.call('del',KEYS[1])
end
-- 失败return0
return 0
